# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d0527a85b119f9ded5642975a236f8226996bc2767faf6dcf9263afc9cce9b4f8aa70579884486b8e9661c51b84a0661662dbe294127523f8d6e57bd8a61367

test:
  secret_key_base: 400421e870c3c5191a4b318361f81504bc90621592200a29ecfc6ebb3ae8139e56192ee4982f00edc739a3f719210745d4f21d38055e028b0254ece9035f9f69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
